Repository duplocloud/terraform-duplocloud-components, pull requests merged in 2024-06, with the labels that each got.

#9 Add support for scale from 0 and spot instances
  modules/eks-nodes/.terraform.lock.hcl
  modules/eks-nodes/main.tf
  modules/eks-nodes/variables.tf
  modules/eks-nodes/versions.tf
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#8 Created a retool bastion module
  examples/retool-bastion/README.md
  examples/retool-bastion/main.tf
  modules/retool-bastion/README.md
  modules/retool-bastion/main.tf
  modules/retool-bastion/outputs.tf
  modules/retool-bastion/variables.tf
  modules/retool-bastion/versions.tf
Labels: documentation, enhancement, Review effort [1-5]: 3

#13 Omer retool5
  modules/retool-bastion/main.tf
Labels: enhancement, Review effort [1-5]: 1
