Repository duplocloud/terraform-duplocloud-components, pull requests merged in 2025-03, with the labels that each got.

#28 fixed hpa null value issue with templates
  .gitignore
  CHANGELOG.md
  modules/loadbalancer/lbconfig.tf
  modules/micro-service/service.tf
  modules/micro-service/templates/container.json
  modules/micro-service/templates/hpa-spec.yaml
Labels: Review effort 2/5

#26 SSM List and Secure plus Env Files
  CHANGELOG.md
  examples/env-file/main.tf
  modules/configuration/aws-secret.tf
  modules/configuration/aws-ssm.tf
  modules/configuration/configmap.tf
  modules/configuration/csi-class.tf
  modules/configuration/main.tf
  modules/configuration/secret.tf
  modules/configuration/tests/configmap.tftest.hcl
  modules/configuration/tests/errors.tftest.hcl
  modules/configuration/tests/files.tftest.hcl
  modules/configuration/tests/main.tftest.hcl
  modules/configuration/tests/secrets.tftest.hcl
  modules/configuration/tests/ssm.tftest.hcl
  modules/configuration/variables.tf
  modules/env-file/README.md
  modules/env-file/main.tf
  modules/env-file/outputs.tf
  modules/env-file/tests/.env
  modules/env-file/tests/errors.tftest.hcl
  modules/env-file/tests/main.tftest.hcl
  modules/env-file/variables.tf
  modules/env-file/versions.tf
Labels: Review effort 3/5

#29 add a gh submod
  .gitignore
  CHANGELOG.md
  examples/gh-config/main.tf
  modules/configuration/github/gh-secret.tf
  modules/configuration/github/gh-variable.tf
  modules/configuration/github/main.tf
  modules/configuration/github/outputs.tf
  modules/configuration/github/variables.tf
  modules/configuration/github/versions.tf
Labels: Review effort 3/5

#33 updates for this module to function on gke autopilot
  modules/micro-service/service.tf
  modules/micro-service/templates/service.json
  modules/micro-service/variables.tf
Labels: Review effort 2/5

#32 adding note on assume role policy
  modules/tenant-role-extension/README.md
Labels: Review effort 1/5

#34 default hhtp get health checks
  CHANGELOG.md
  modules/micro-service/service.tf
  modules/micro-service/templates/hpa-spec.yaml
  modules/micro-service/templates/service.json
  modules/micro-service/templates/service.yaml
  modules/micro-service/variables.tf
Labels: Review effort 2/5
